name: psyplot-presi
channels:
    - conda-forge
dependencies:
    - python=3.11
    - jupyter_contrib_nbextensions
    - jupyter
    - rise
    - ipympl
    - dask
    - pip
    - pyinterp
    - scikit-learn
    - psy-view=1.5.0
    # mybinder has a problem with upgrading ipython, so we fix the version here
    - ipython=8.16.1
    # Required for jupyter-desktop-server
    - websockify
    - pip:
        - jupyter-desktop-server
        - psy-ugrid
        - psy-transect
